apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rjnt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rjnt
    app.kubernetes.io/part-of: test-app-zfwn
  name: test-component-rjnt
  namespace: build-e2e-ohiy-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-rjnt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-rjnt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:f5971713fca74b3083cae80a907b3058
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
